var searchData=
[
  ['dataexportbutton_0',['DataExportButton',['../class_d_i_c_o_m_app_1_1_data_export_button.html',1,'DICOMApp.DataExportButton'],['../class_d_i_c_o_m_app_1_1_data_export_button.html#a4bc7b599a637bbcdf8d87023e52666b6',1,'DICOMApp.DataExportButton.DataExportButton()']]],
  ['dataexportbutton_2eaxaml_2ecs_1',['DataExportButton.axaml.cs',['../_data_export_button_8axaml_8cs.html',1,'']]],
  ['dataexporthandler_2',['DataExportHandler',['../class_d_i_c_o_m_app_1_1_repository_1_1_data_export_handler.html',1,'DICOMApp.Repository.DataExportHandler'],['../class_d_i_c_o_m_app_1_1_repository_1_1_data_export_handler.html#ab733feb1674918335a3dd8ea12ce1657',1,'DICOMApp.Repository.DataExportHandler.DataExportHandler()']]],
  ['dataexporthandler_2ecs_3',['DataExportHandler.cs',['../_data_export_handler_8cs.html',1,'']]],
  ['dicom_20z_20możliwością_20podłączenia_20pluginów_20ai_4',['Aplikacja do przeglądania i edycji obrazów DICOM z możliwością podłączenia pluginów AI',['../dir_1afafb9ef185eaac7646cb0f4cd779d1.html#autotoc_md0',1,'']]],
  ['dicomapp_5',['DICOMApp',['../namespace_d_i_c_o_m_app.html',1,'']]],
  ['dicomapp_2eassemblyinfo_2ecs_6',['DICOMApp.AssemblyInfo.cs',['../_a_r_m64_2_debug_2net9_80_2_d_i_c_o_m_app_8_assembly_info_8cs.html',1,'(Globalna przestrzeń nazw)'],['../_a_r_m64_2_release_2net9_80_2_d_i_c_o_m_app_8_assembly_info_8cs.html',1,'(Globalna przestrzeń nazw)'],['../_debug_2net9_80-windows_2_d_i_c_o_m_app_8_assembly_info_8cs.html',1,'(Globalna przestrzeń nazw)'],['../_debug_2net9_80-windows10_80_817763_80_2_d_i_c_o_m_app_8_assembly_info_8cs.html',1,'(Globalna przestrzeń nazw)'],['../_debug_2net9_80-windows7_80_2_d_i_c_o_m_app_8_assembly_info_8cs.html',1,'(Globalna przestrzeń nazw)'],['../_debug_2net9_80_2_d_i_c_o_m_app_8_assembly_info_8cs.html',1,'(Globalna przestrzeń nazw)'],['../_release_2net9_80_2_d_i_c_o_m_app_8_assembly_info_8cs.html',1,'(Globalna przestrzeń nazw)'],['../_win32_2_debug_2net9_80_2_d_i_c_o_m_app_8_assembly_info_8cs.html',1,'(Globalna przestrzeń nazw)'],['../_win32_2_release_2net9_80_2_d_i_c_o_m_app_8_assembly_info_8cs.html',1,'(Globalna przestrzeń nazw)']]],
  ['dicomapp_3a_3abehaviors_7',['Behaviors',['../namespace_d_i_c_o_m_app_1_1_behaviors.html',1,'DICOMApp']]],
  ['dicomapp_3a_3adata_8',['Data',['../namespace_d_i_c_o_m_app_1_1_data.html',1,'DICOMApp']]],
  ['dicomapp_3a_3adicom_9',['DICOM',['../namespace_d_i_c_o_m_app_1_1_d_i_c_o_m.html',1,'DICOMApp']]],
  ['dicomapp_3a_3ainterfaces_10',['Interfaces',['../namespace_d_i_c_o_m_app_1_1_interfaces.html',1,'DICOMApp']]],
  ['dicomapp_3a_3amlmodel_11',['MLModel',['../namespace_d_i_c_o_m_app_1_1_m_l_model.html',1,'DICOMApp']]],
  ['dicomapp_3a_3aother_12',['Other',['../namespace_d_i_c_o_m_app_1_1_other.html',1,'DICOMApp']]],
  ['dicomapp_3a_3arepository_13',['Repository',['../namespace_d_i_c_o_m_app_1_1_repository.html',1,'DICOMApp']]],
  ['dicomapp_3a_3aservices_14',['Services',['../namespace_d_i_c_o_m_app_1_1_services.html',1,'DICOMApp']]],
  ['dicomapp_3a_3autils_15',['Utils',['../namespace_d_i_c_o_m_app_1_1_utils.html',1,'DICOMApp']]],
  ['dicomapp_3a_3aviewmodel_16',['ViewModel',['../namespace_d_i_c_o_m_app_1_1_view_model.html',1,'DICOMApp']]],
  ['dicomapp_3a_3aviewmodel_3a_3alines_17',['Lines',['../namespace_d_i_c_o_m_app_1_1_view_model_1_1_lines.html',1,'DICOMApp::ViewModel']]],
  ['dicomapp_3a_3aviews_18',['Views',['../namespace_d_i_c_o_m_app_1_1_views.html',1,'DICOMApp']]],
  ['dicomdirectoryhandler_19',['DICOMDirectoryHandler',['../class_d_i_c_o_m_app_1_1_utils_1_1_d_i_c_o_m_directory_handler.html',1,'DICOMApp::Utils']]],
  ['dicomdirectoryhandler_2ecs_20',['DICOMDirectoryHandler.cs',['../_d_i_c_o_m_directory_handler_8cs.html',1,'']]],
  ['dicomimagedata_21',['DICOMImageData',['../class_d_i_c_o_m_app_1_1_data_1_1_d_i_c_o_m_image_data.html',1,'DICOMApp.Data.DICOMImageData'],['../class_d_i_c_o_m_app_1_1_data_1_1_d_i_c_o_m_image_data.html#a2bf55ca2b2fbe189adce928560950326',1,'DICOMApp.Data.DICOMImageData.DICOMImageData()']]],
  ['dicomimagedata_2ecs_22',['DICOMImageData.cs',['../_d_i_c_o_m_image_data_8cs.html',1,'']]],
  ['dicomimageloader_23',['DICOMImageLoader',['../class_d_i_c_o_m_app_1_1_utils_1_1_d_i_c_o_m_image_loader.html',1,'DICOMApp::Utils']]],
  ['dicomimageloader_2ecs_24',['DICOMImageLoader.cs',['../_d_i_c_o_m_image_loader_8cs.html',1,'']]],
  ['dicominformationview_25',['DicomInformationView',['../class_d_i_c_o_m_app_1_1_dicom_information_view.html',1,'DICOMApp.DicomInformationView'],['../class_d_i_c_o_m_app_1_1_dicom_information_view.html#a51c4a4426d4c259a7317f71f8a6e19ea',1,'DICOMApp.DicomInformationView.DicomInformationView()']]],
  ['dicominformationview_2eaxaml_2ecs_26',['DicomInformationView.axaml.cs',['../_dicom_information_view_8axaml_8cs.html',1,'']]],
  ['dicommetadata_27',['DICOMMetadata',['../class_d_i_c_o_m_app_1_1_data_1_1_d_i_c_o_m_metadata.html',1,'DICOMApp.Data.DICOMMetadata'],['../class_d_i_c_o_m_app_1_1_data_1_1_d_i_c_o_m_metadata.html#a75626c4bed869b3523931fa3becf032b',1,'DICOMApp.Data.DICOMMetadata.DICOMMetadata()']]],
  ['dicommetadata_2ecs_28',['DICOMMetadata.cs',['../_d_i_c_o_m_metadata_8cs.html',1,'']]],
  ['dicomreader_29',['DICOMReader',['../class_d_i_c_o_m_app_1_1_utils_1_1_d_i_c_o_m_reader.html',1,'DICOMApp::Utils']]],
  ['dicomreader_2ecs_30',['DICOMReader.cs',['../_d_i_c_o_m_reader_8cs.html',1,'']]],
  ['dicomscalerfactory_31',['DICOMScalerFactory',['../class_d_i_c_o_m_app_1_1_utils_1_1_d_i_c_o_m_scaler_factory.html',1,'DICOMApp::Utils']]],
  ['dicomscalerfactory_2ecs_32',['DICOMScalerFactory.cs',['../_d_i_c_o_m_scaler_factory_8cs.html',1,'']]],
  ['dispose_33',['Dispose',['../class_d_i_c_o_m_app_1_1_repository_1_1_s_q_l_data_base_connection_handler.html#ada1da8525956997e0a7df27ee84ed026',1,'DICOMApp.Repository.SQLDataBaseConnectionHandler.Dispose(bool disposing)'],['../class_d_i_c_o_m_app_1_1_repository_1_1_s_q_l_data_base_connection_handler.html#ada65b29e8d7acd9df4585a8d38a1d3da',1,'DICOMApp.Repository.SQLDataBaseConnectionHandler.Dispose()'],['../class_d_i_c_o_m_app_1_1_repository_1_1_s_q_l_data_base_handler.html#a9179c4759202b57534009c628d104b74',1,'DICOMApp.Repository.SQLDataBaseHandler.Dispose(bool disposing)'],['../class_d_i_c_o_m_app_1_1_repository_1_1_s_q_l_data_base_handler.html#a4a93c94b03ced1b42e4b6e7ddd976282',1,'DICOMApp.Repository.SQLDataBaseHandler.Dispose()']]],
  ['disposedvalue_34',['disposedValue',['../class_d_i_c_o_m_app_1_1_repository_1_1_s_q_l_data_base_connection_handler.html#a2389469c1971cae0d25e6b1d1fb20176',1,'DICOMApp.Repository.SQLDataBaseConnectionHandler.disposedValue'],['../class_d_i_c_o_m_app_1_1_repository_1_1_s_q_l_data_base_handler.html#a9e719911a92f731b6cf6f0c3d1767bfc',1,'DICOMApp.Repository.SQLDataBaseHandler.disposedValue']]],
  ['do_20przeglądania_20i_20edycji_20obrazów_20dicom_20z_20możliwością_20podłączenia_20pluginów_20ai_35',['Aplikacja do przeglądania i edycji obrazów DICOM z możliwością podłączenia pluginów AI',['../dir_1afafb9ef185eaac7646cb0f4cd779d1.html#autotoc_md0',1,'']]],
  ['dokumentacja_36',['Dokumentacja',['../dir_1afafb9ef185eaac7646cb0f4cd779d1.html#autotoc_md1',1,'']]],
  ['double_37',['double',['../class_d_i_c_o_m_app_1_1_view_model_1_1_magnified_image_view_model.html#a1ac3f11595784a566ec7234402f19567',1,'DICOMApp::ViewModel::MagnifiedImageViewModel']]]
];
